name: Docker Image CI

from: php:7.4-apache

# Set the working directory in the container
workdir: /var/www/html

# Copy the PHP application files to the working directory
copy: . /var/www/html

# Install PHP-Mailer and other dependencies
run: apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    zip \
    unzip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd

# Enable the Apache rewrite module for clean URLs
run: a2enmod rewrite

# Set up the virtual host configuration
copy: ./apache-config.conf /etc/apache2/sites-available/000-default.conf

# Import database schema
copy: ./database_schema/hhh_db.sql /docker-entrypoint-initdb.d/hhh_db.sql

# Expose port 80 to the outside world
expose: 80

# Define environment variables for MySQL connection
env: MYSQL_ROOT_PASSWORD=root_password
env: MYSQL_DATABASE=hhh_db
env: MYSQL_USER=db_user
env: MYSQL_PASSWORD=db_password

# Set up environment variables for the PHP application
env: PHP_MAILER_VERSION=6.5.0

# Set the entrypoint for the container
entrypoint: ["/usr/local/bin/docker-php-entrypoint"]

# Start the Apache web server when the container launches
cmd: ["apache2-foreground"]
